name: base
channels:
  - defaults
dependencies:
  - antropy==0.1.5
  - anyio==3.6.2
  - appdirs==1.4.4
  - appnope==0.1.3
  - argon2-cffi==21.3.0
  - argon2-cffi-bindings==21.2.0
  - asttokens==2.2.1
  - attrs==22.2.0
  - backcall==0.2.0
  - beautifulsoup4==4.11.2
  - bleach==6.0.0
  - certifi==2022.12.7
  - cffi==1.15.1
  - charset-normalizer==2.1.1
  - cloudpickle==2.2.0
  - comm==0.1.2
  - contourpy==1.0.6
  - cryptography==38.0.4
  - cycler==0.11.0
  - debugpy==1.6.6
  - decorator==5.1.1
  - defusedxml==0.7.1
  - executing==1.2.0
  - fastjsonschema==2.16.2
  - fonttools==4.38.0
  - idna==3.4
  - imageio==2.22.4
  - importlib-metadata==5.1.0
  - importlib-resources==5.10.2
  - ipykernel==6.21.1
  - ipython==8.9.0
  - ipython-genutils==0.2.0
  - ipywidgets==8.0.4
  - jedi==0.18.2
  - Jinja2==3.1.2
  - joblib==1.2.0
  - jsonschema==4.17.3
  - jupyter==1.0.0
  - jupyter-client==8.0.2
  - jupyter-console==6.4.4
  - jupyter-core==5.2.0
  - jupyter-events==0.6.3
  - jupyter-server==2.2.1
  - jupyter-server-terminals==0.4.4
  - jupyterlab-pygments==0.2.2
  - jupyterlab-widgets==3.0.5
  - kiwisolver==1.4.4
  - lime==0.2.0.1
  - llvmlite==0.39.1
  - lxml==4.9.2
  - MarkupSafe==2.1.2
  - matplotlib==3.6.2
  - matplotlib-inline==0.1.6
  - mistune==2.0.4
  - multitasking==0.0.11
  - nbclassic==0.5.1
  - nbclient==0.7.2
  - nbconvert==7.2.9
  - nbformat==5.7.3
  - nest-asyncio==1.5.6
  - networkx==2.8.8
  - notebook==6.5.2
  - notebook-shim==0.2.2
  - numba==0.56.4
  - numpy==1.23.5
  - packaging==22.0
  - pandas==1.5.2
  - pandas-datareader==0.10.0
  - pandocfilters==1.5.0
  - parso==0.8.3
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - Pillow==9.3.0
  - pkgutil-resolve-name==1.3.10
  - platformdirs==3.0.0
  - prometheus-client==0.16.0
  - prompt-toolkit==3.0.36
  - psutil==5.9.4
  - ptyprocess==0.7.0
  - pure-eval==0.2.2
  - pycparser==2.21
  - Pygments==2.14.0
  - pyparsing==3.0.9
  - pyrsistent==0.19.3
  - python-dateutil==2.8.2
  - python-json-logger==2.0.4
  - pytz==2022.7
  - PyWavelets==1.4.1
  - PyYAML==6.0
  - pyzmq==25.0.0
  - qtconsole==5.4.0
  - QtPy==2.3.0
  - requests==2.28.1
  - rfc3339-validator==0.1.4
  - rfc3986-validator==0.1.1
  - scikit-image==0.19.3
  - scikit-learn==1.2.0
  - scipy==1.9.3
  - Send2Trash==1.8.0
  - shap==0.41.0
  - six==1.16.0
  - sklearn==0.0.post1
  - slicer==0.0.7
  - sniffio==1.3.0
  - soupsieve==2.3.2.post1
  - stack-data==0.6.2
  - stochastic==0.7.0
  - TA-Lib==0.4.25
  - terminado==0.17.1
  - threadpoolctl==3.1.0
  - tifffile==2022.10.10
  - tinycss2==1.2.1
  - tornado==6.2
  - tqdm==4.64.1
  - traitlets==5.9.0
  - urllib3==1.26.13
  - wcwidth==0.2.6
  - webencodings==0.5.1
  - websocket-client==1.5.1
  - widgetsnbextension==4.0.5
  - yfinance==0.1.93
  - zipp==3.11.0
- prefix: /opt/anaconda3

